package OOP.JobPortal.ResumeMatchingSystem.Services.impl;

import OOP.JobPortal.ResumeMatchingSystem.Entities.Resume;
import OOP.JobPortal.ResumeMatchingSystem.Exceptions.BusinessException;
import OOP.JobPortal.ResumeMatchingSystem.Services.AbstractPdfService;
import com.itextpdf.html2pdf.ConverterProperties;
import com.itextpdf.html2pdf.HtmlConverter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

/**
 * ============================================================
 * PdfService  –  HTML → PDF Conversion
 * ============================================================
 *
 * WEEK 3 – File Handling:
 *   This service generates a PDF file from HTML content and returns
 *   it as a byte array. The controller streams these bytes to the
 *   browser as a downloadable file.
 *
 *   This satisfies the Week 3 requirement of "file handling" —
 *   generating a file (PDF) and delivering it to the user.
 *
 * WEEK 12 – Exception Handling:
 *   PDF generation can fail if iText encounters malformed HTML.
 *   We catch that and wrap it in a BusinessException with a
 *   user-friendly message.
 *
 * LIBRARY USED: iText html2pdf
 *   Converts HTML + CSS to a PDF document.
 *   The HTML generated by ClaudeAiService is passed directly here.
 * ============================================================
 */
@Service
public class PdfService extends AbstractPdfService {

    /**
     * Generates a PDF from the resume's AI-generated HTML content.
     *
     * WEEK 3 – File Handling:
     *   ByteArrayOutputStream acts as an in-memory "file".
     *   We write the PDF bytes to it, then return the byte array.
     *   The controller sets Content-Type: application/pdf and
     *   Content-Disposition: attachment so the browser downloads it.
     *
     * @param resume the resume entity containing the HTML to convert
     * @return       PDF content as a byte array
     * @throws BusinessException if PDF generation fails
     */
    public byte[] generateResumePdf(Resume resume) {

        // Get the HTML — use AI-generated if available, fallback otherwise
        String html = resume.getAiGeneratedHtml();
        if (html == null || html.isBlank()) {
            // Build a minimal HTML if AI hasn't generated one yet
            html = buildMinimalHtml(resume);
        }

        try {
            // ByteArrayOutputStream is an in-memory stream — no temp files needed
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            // Configure iText conversion properties
            ConverterProperties properties = new ConverterProperties();

            // Convert the HTML string to PDF bytes
            HtmlConverter.convertToPdf(html, outputStream, properties);

            return outputStream.toByteArray();

        } catch (Exception e) {
            // WEEK 12 – Catch block: wrap the iText exception in our custom one
            throw new BusinessException(
                    "Failed to generate PDF for resume: " + e.getMessage());
        }
    }

    /**
     * Builds a minimal HTML resume when no AI version exists.
     * This is a fallback for cases where the seeker never called generate-ai.
     *
     * WEEK 2 – Strings: uses String.format() for clean HTML template generation.
     *
     * @param resume the resume with raw data
     * @return       minimal HTML string
     */
    private String buildMinimalHtml(Resume resume) {

        String name     = resume.getJobSeeker().getFullName();
        String email    = resume.getJobSeeker().getEmail();
        String skills   = resume.getSkills()   != null ? resume.getSkills()   : "Not specified";
        String education = resume.getEducation() != null ? resume.getEducation() : "—";
        String experience = resume.getWorkExperience() != null ? resume.getWorkExperience() : "—";

        return String.format(
                "<html><body style='font-family:Arial;padding:40px;'>"
                        + "<h1 style='color:#1a3c6e;'>%s</h1>"
                        + "<p>%s</p>"
                        + "<h2 style='color:#1a3c6e;'>Skills</h2><p>%s</p>"
                        + "<h2 style='color:#1a3c6e;'>Education</h2><p>%s</p>"
                        + "<h2 style='color:#1a3c6e;'>Experience</h2><p>%s</p>"
                        + "</body></html>",
                escapeHtml(name),
                escapeHtml(email),
                escapeHtml(skills),
                escapeHtml(education),
                escapeHtml(experience)
        );
    }

    /**
     * Escapes HTML special characters to prevent rendering issues in the PDF.
     *
     * @param input raw string
     * @return      HTML-safe string
     */
    private String escapeHtml(String input) {
        if (input == null) {
            return "";
        }
        return input
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;");
    }
}
