package OOP.JobPortal.ResumeMatchingSystem.Services.impl;

import OOP.JobPortal.ResumeMatchingSystem.DTOs.request.ResumeRequest;
import OOP.JobPortal.ResumeMatchingSystem.DTOs.response.ResumeResponse;
import OOP.JobPortal.ResumeMatchingSystem.Entities.JobSeeker;
import OOP.JobPortal.ResumeMatchingSystem.Entities.Resume;
import OOP.JobPortal.ResumeMatchingSystem.Exceptions.ResourceNotFoundException;
import OOP.JobPortal.ResumeMatchingSystem.Repositories.JobSeekerRepository;
import OOP.JobPortal.ResumeMatchingSystem.Repositories.ResumeRepository;
import OOP.JobPortal.ResumeMatchingSystem.Services.AbstractResumeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * ResumeService – saves resume data and generates PDF.
 *
 * PDF is generated by PdfService using a professional HTML template.
 * No AI API needed – PdfService builds the template from resume fields directly.
 */
@Service
public class ResumeService extends AbstractResumeService {

    @Autowired private ResumeRepository    resumeRepo;
    @Autowired private JobSeekerRepository seekerRepo;
    @Autowired private PdfService          pdfService;

    @Transactional
    public ResumeResponse saveOrUpdate(Long seekerId, ResumeRequest req) {
        JobSeeker seeker = seekerRepo.findById(seekerId)
                .orElseThrow(() -> new ResourceNotFoundException("JobSeeker", seekerId));

        Resume resume = resumeRepo.findByJobSeekerId(seekerId)
                .orElseGet(() -> new Resume(seeker));

        // Core sections
        if (req.getSkills()         != null) resume.setSkills(req.getSkills());
        if (req.getWorkExperience() != null) resume.setWorkExperience(req.getWorkExperience());
        if (req.getEducation()      != null) resume.setEducation(req.getEducation());
        if (req.getCertifications() != null) resume.setCertifications(req.getCertifications());
        if (req.getLanguages()      != null) resume.setLanguages(req.getLanguages());

        // Extended sections
        if (req.getProjects()             != null) resume.setProjects(req.getProjects());
        if (req.getAwards()               != null) resume.setAwards(req.getAwards());
        if (req.getVolunteerWork()        != null) resume.setVolunteerWork(req.getVolunteerWork());
        if (req.getPublications()         != null) resume.setPublications(req.getPublications());
        if (req.getReferencesText()       != null) resume.setReferencesText(req.getReferencesText());
        if (req.getTotalExperienceYears() != null) resume.setTotalExperienceYears(req.getTotalExperienceYears());

        // Links
        if (req.getPortfolioUrl() != null) resume.setPortfolioUrl(req.getPortfolioUrl());
        if (req.getLinkedinUrl()  != null) resume.setLinkedinUrl(req.getLinkedinUrl());
        if (req.getGithubUrl()    != null) resume.setGithubUrl(req.getGithubUrl());

        return ResumeResponse.from(resumeRepo.save(resume));
    }

    public byte[] getResumePdfBytes(Long seekerId) {
        Resume resume = resumeRepo.findByJobSeekerId(seekerId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No resume found for seeker with id: " + seekerId));
        return pdfService.generateResumePdf(resume);
    }

    public ResumeResponse getBySeekerId(Long seekerId) {
        Resume resume = resumeRepo.findByJobSeekerId(seekerId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No resume found for seeker with id: " + seekerId));
        return ResumeResponse.from(resume);
    }
}